# Generated by Django 5.2a1 on 2025-02-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.CharField(max_length=255, verbose_name='Изображение'),
        ),
    ]
