# Generated by Django 5.2a1 on 2025-02-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_flower_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(upload_to='static/general/image', verbose_name='Изображение'),
        ),
    ]
